version: "3.8"

services:
  # PostgreSQL база данных
  db:
    image: postgres:12
    container_name: vpn_db
    restart: always
    environment:
      POSTGRES_DB: vpn_bot_db
      POSTGRES_USER: vpn_bot_user
      POSTGRES_PASSWORD: post123
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./SQL:/docker-entrypoint-initdb.d
    networks:
      - vpn_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vpn_bot_user -d vpn_bot_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  # REST API для управления WireGuard
  wgrest:
    image: ghcr.io/embarkstudios/wgrest:latest
    container_name: wgrest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      - NET_RAW
    network_mode: host  # доступ к ядру WireGuard
    environment:
      WGREST_LISTEN: 0.0.0.0:8080
      WGREST_DATA_DIR: /var/lib/wgrest
      WGREST_STATIC_AUTH_TOKEN: "b1g5r4nd0mt0k3n12345"
    volumes:
      - ./wgrest_data:/var/lib/wgrest
    restart: unless-stopped

  # Telegram бот
  vpn_bot:
    build: ./vpn_bot
    container_name: vpn_bot
    depends_on:
      db:
        condition: service_healthy
      wgrest:
        condition: service_started
    env_file:
      - ./vpn_bot/.env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vpn_bot_db
      DB_USER: vpn_bot_user
      DB_PASSWORD: post123
      WGREST_URL: http://host.docker.internal:8080
      WGREST_AUTH_TOKEN: b1g5r4nd0mt0k3n12345
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - vpn_network
    restart: unless-stopped

networks:
  vpn_network:
    driver: bridge

volumes:
  db_data:
  wgrest_data:
